"""add transaction fingerprint

Revision ID: a2b1c5294ab6
Revises: b97f02998a77
Create Date: 2026-09-02 00:20:40.698532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b1c5294ab6'
down_revision: Union[str, Sequence[str], None] = 'b97f02998a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fingerprint', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'transactions', ['fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'fingerprint')
    # ### end Alembic commands ###
