"""add transaction type to transactions

Revision ID: b1ecbaba7c9f
Revises: 736e565e479c
Create Date: 2026-09-02 19:26:06.149022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ecbaba7c9f'
down_revision: Union[str, Sequence[str], None] = '736e565e479c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###
