"""add persistent api configuration audit

Revision ID: b35bd7f51ab6
Revises: fa124f53f7f3
Create Date: 2026-09-03 00:53:43.566010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35bd7f51ab6'
down_revision: Union[str, Sequence[str], None] = 'fa124f53f7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('resource_public_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_audit_events_action'), 'api_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_api_audit_events_actor_user_id'), 'api_audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_api_audit_events_created_at'), 'api_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_audit_events_event_type'), 'api_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_api_audit_events_outcome'), 'api_audit_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_api_audit_events_public_id'), 'api_audit_events', ['public_id'], unique=True)
    op.create_index(op.f('ix_api_audit_events_resource_public_id'), 'api_audit_events', ['resource_public_id'], unique=False)
    op.create_index(op.f('ix_api_audit_events_resource_type'), 'api_audit_events', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_audit_events_resource_type'), table_name='api_audit_events')
    op.drop_index(op.f('ix_api_audit_events_resource_public_id'), table_name='api_audit_events')
    op.drop_index(op.f('ix_api_audit_events_public_id'), table_name='api_audit_events')
    op.drop_index(op.f('ix_api_audit_events_outcome'), table_name='api_audit_events')
    op.drop_index(op.f('ix_api_audit_events_event_type'), table_name='api_audit_events')
    op.drop_index(op.f('ix_api_audit_events_created_at'), table_name='api_audit_events')
    op.drop_index(op.f('ix_api_audit_events_actor_user_id'), table_name='api_audit_events')
    op.drop_index(op.f('ix_api_audit_events_action'), table_name='api_audit_events')
    op.drop_table('api_audit_events')
    # ### end Alembic commands ###
