"""add category rules and merchant aliases

Revision ID: ec29fb8c7dae
Revises: b1ecbaba7c9f
Create Date: 2026-09-02 20:16:41.065125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec29fb8c7dae'
down_revision: Union[str, Sequence[str], None] = 'b1ecbaba7c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority')
    )
    op.create_table('merchant_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_aliases')
    op.drop_table('category_rules')
    # ### end Alembic commands ###
